DATA = [
# ================= アフリカ 42 =================
("ギザのピラミッド","Great Pyramid of Giza","eg","エジプト","africa",1),
("カイロ・タハリール広場","Tahrir Square, Cairo","eg","エジプト","africa",1),
("ルクソール神殿","Luxor Temple, Egypt","eg","エジプト","africa",1),
("ケープタウン・ウォーターフロント","V&A Waterfront, Cape Town","za","南アフリカ","africa",1),
("テーブルマウンテン","Table Mountain, Cape Town","za","南アフリカ","africa",1),
("ヨハネスブルグ","Nelson Mandela Square, Johannesburg","za","南アフリカ","africa",1),
("マラケシュ・ジャマエルフナ","Jemaa el-Fnaa, Marrakesh","ma","モロッコ","africa",1),
("カサブランカ","Hassan II Mosque, Casablanca","ma","モロッコ","africa",1),
("ナイロビ","Kenyatta Avenue, Nairobi","ke","ケニア","africa",1),
("チュニス","Avenue Habib Bourguiba, Tunis","tn","チュニジア","africa",1),
("ダーバン","Durban Beachfront, KwaZulu-Natal","za","南アフリカ","africa",2),
("プレトリア","Church Square, Pretoria","za","南アフリカ","africa",2),
("ステレンボッシュ","Stellenbosch, Western Cape","za","南アフリカ","africa",2),
("フェズ","Fes el Bali, Fez","ma","モロッコ","africa",2),
("ラバト","Kasbah of the Udayas, Rabat","ma","モロッコ","africa",2),
("タンジェ","Tangier, Morocco","ma","モロッコ","africa",2),
("アレクサンドリア","Corniche, Alexandria","eg","エジプト","africa",2),
("アスワン","Aswan, Egypt","eg","エジプト","africa",2),
("モンバサ","Mombasa, Kenya","ke","ケニア","africa",2),
("アルーシャ","Arusha, Tanzania","tz","タンザニア","africa",2),
("ダルエスサラーム","Dar es Salaam, Tanzania","tz","タンザニア","africa",2),
("アクラ","Independence Square, Accra","gh","ガーナ","africa",2),
("ダカール","Place de l'Independance, Dakar","sn","セネガル","africa",2),
("ラゴス","Lagos Island, Nigeria","ng","ナイジェリア","africa",2),
("ポートエリザベス","Gqeberha, Eastern Cape","za","南アフリカ","africa",3),
("ブルームフォンテーン","Bloemfontein, Free State","za","南アフリカ","africa",3),
("キンバリー","Kimberley, Northern Cape","za","南アフリカ","africa",3),
("ジョージ","George, Western Cape","za","南アフリカ","africa",3),
("クニスナ","Knysna, Western Cape","za","南アフリカ","africa",3),
("ハボローネ","Gaborone, Botswana","bw","ボツワナ","africa",3),
("マウン","Maun, Botswana","bw","ボツワナ","africa",3),
("ウィントフック","Windhoek, Namibia","na","ナミビア","africa",3),
("スワコプムント","Swakopmund, Namibia","na","ナミビア","africa",3),
("マセル","Maseru, Lesotho","ls","レソト","africa",3),
("ムババーネ","Mbabane, Eswatini","sz","エスワティニ","africa",3),
("キガリ","Kigali, Rwanda","rw","ルワンダ","africa",3),
("カンパラ","Kampala, Uganda","ug","ウガンダ","africa",3),
("エンテベ","Entebbe, Uganda","ug","ウガンダ","africa",3),
("キスム","Kisumu, Kenya","ke","ケニア","africa",3),
("ザンジバル・ストーンタウン","Stone Town, Zanzibar","tz","タンザニア","africa",3),
("クマシ","Kumasi, Ghana","gh","ガーナ","africa",3),
("スース","Sousse, Tunisia","tn","チュニジア","africa",3),
# ================= オセアニア 40 =================
("シドニー・オペラハウス","Sydney Opera House","au","オーストラリア","oceania",1),
("シドニー・ハーバーブリッジ","Sydney Harbour Bridge","au","オーストラリア","oceania",1),
("メルボルン・フェデレーションスクエア","Federation Square, Melbourne","au","オーストラリア","oceania",1),
("ゴールドコースト","Surfers Paradise, Gold Coast","au","オーストラリア","oceania",1),
("ウルル","Uluru, Northern Territory","au","オーストラリア","oceania",1),
("グレートオーシャンロード","Twelve Apostles, Victoria","au","オーストラリア","oceania",1),
("ボンダイビーチ","Bondi Beach, Sydney","au","オーストラリア","oceania",1),
("オークランド・スカイタワー","Sky Tower, Auckland","nz","ニュージーランド","oceania",1),
("クイーンズタウン","Queenstown, Otago","nz","ニュージーランド","oceania",1),
("ロトルア","Rotorua, Bay of Plenty","nz","ニュージーランド","oceania",1),
("ブリスベン","South Bank, Brisbane","au","オーストラリア","oceania",2),
("パース","Elizabeth Quay, Perth","au","オーストラリア","oceania",2),
("アデレード","Rundle Mall, Adelaide","au","オーストラリア","oceania",2),
("キャンベラ","Parliament House, Canberra","au","オーストラリア","oceania",2),
("ホバート","Salamanca Place, Hobart","au","オーストラリア","oceania",2),
("ケアンズ","Cairns Esplanade, Queensland","au","オーストラリア","oceania",2),
("ダーウィン","Mindil Beach, Darwin","au","オーストラリア","oceania",2),
("バイロンベイ","Byron Bay, New South Wales","au","オーストラリア","oceania",2),
("ウェリントン","Cuba Street, Wellington","nz","ニュージーランド","oceania",2),
("クライストチャーチ","Cathedral Square, Christchurch","nz","ニュージーランド","oceania",2),
("ダニーデン","The Octagon, Dunedin","nz","ニュージーランド","oceania",2),
("ネーピア","Napier, Hawke's Bay","nz","ニュージーランド","oceania",2),
("タウポ","Taupo, Waikato","nz","ニュージーランド","oceania",2),
("ヌメア","Noumea, New Caledonia","nc","ニューカレドニア","oceania",2),
("ニューカッスル","Newcastle, New South Wales","au","オーストラリア","oceania",3),
("ウーロンゴン","Wollongong, New South Wales","au","オーストラリア","oceania",3),
("ジーロング","Geelong, Victoria","au","オーストラリア","oceania",3),
("バララット","Ballarat, Victoria","au","オーストラリア","oceania",3),
("ベンディゴ","Bendigo, Victoria","au","オーストラリア","oceania",3),
("トゥーンバ","Toowoomba, Queensland","au","オーストラリア","oceania",3),
("タウンズビル","Townsville, Queensland","au","オーストラリア","oceania",3),
("マッカイ","Mackay, Queensland","au","オーストラリア","oceania",3),
("オールバニ","Albany, Western Australia","au","オーストラリア","oceania",3),
("カルグーリー","Kalgoorlie, Western Australia","au","オーストラリア","oceania",3),
("アリススプリングス","Alice Springs, Northern Territory","au","オーストラリア","oceania",3),
("ロンセストン","Launceston, Tasmania","au","オーストラリア","oceania",3),
("ハミルトン","Hamilton, Waikato","nz","ニュージーランド","oceania",3),
("パーマストンノース","Palmerston North, Manawatu","nz","ニュージーランド","oceania",3),
("インバーカーギル","Invercargill, Southland","nz","ニュージーランド","oceania",3),
("ネルソン","Nelson, New Zealand","nz","ニュージーランド","oceania",3),
]
