# (表示名, 検索クエリ, 国コード, 国名, エリア, 難易度)
DATA = [
# ================= 日本 48 =================
("渋谷スクランブル交差点","Shibuya Crossing, Tokyo","jp","日本","japan",1),
("浅草・雷門","Kaminarimon, Asakusa, Tokyo","jp","日本","japan",1),
("東京タワー","Tokyo Tower, Minato, Tokyo","jp","日本","japan",1),
("道頓堀","Dotonbori, Osaka","jp","日本","japan",1),
("大阪城公園","Osaka Castle Park, Osaka","jp","日本","japan",1),
("京都・清水坂","Kiyomizuzaka, Higashiyama, Kyoto","jp","日本","japan",1),
("奈良公園","Nara Park, Nara","jp","日本","japan",1),
("宮島・厳島神社","Itsukushima Shrine, Hatsukaichi","jp","日本","japan",1),
("河口湖（富士山）","Kawaguchiko Station, Fujikawaguchiko","jp","日本","japan",1),
("札幌・時計台","Sapporo Clock Tower","jp","日本","japan",1),
("那覇・国際通り","Kokusai Dori, Naha","jp","日本","japan",1),
("横浜・赤レンガ倉庫","Yokohama Red Brick Warehouse","jp","日本","japan",1),
("京都・祇園","Gion, Higashiyama, Kyoto","jp","日本","japan",2),
("神戸・北野異人館","Kitano Ijinkan, Kobe","jp","日本","japan",2),
("名古屋・栄","Sakae, Naka-ku, Nagoya","jp","日本","japan",2),
("福岡・天神","Tenjin, Chuo-ku, Fukuoka","jp","日本","japan",2),
("広島・平和記念公園","Hiroshima Peace Memorial Park","jp","日本","japan",2),
("仙台・定禅寺通","Jozenji-dori, Sendai","jp","日本","japan",2),
("金沢・ひがし茶屋街","Higashi Chaya District, Kanazawa","jp","日本","japan",2),
("長崎・グラバー園","Glover Garden, Nagasaki","jp","日本","japan",2),
("松本城","Matsumoto Castle","jp","日本","japan",2),
("日光東照宮","Nikko Toshogu","jp","日本","japan",2),
("鎌倉・小町通り","Komachi-dori, Kamakura","jp","日本","japan",2),
("箱根湯本","Hakone-Yumoto Station","jp","日本","japan",2),
("熱海","Atami Station, Shizuoka","jp","日本","japan",2),
("高山・古い町並み","Sannomachi, Takayama, Gifu","jp","日本","japan",2),
("倉敷美観地区","Kurashiki Bikan Historical Quarter","jp","日本","japan",2),
("別府温泉","Beppu Station, Oita","jp","日本","japan",2),
("函館・元町","Motomachi, Hakodate","jp","日本","japan",2),
("小樽運河","Otaru Canal","jp","日本","japan",2),
("秋田市","Akita Station, Akita","jp","日本","japan",3),
("山形市","Yamagata Station, Yamagata","jp","日本","japan",3),
("富山市","Toyama Station, Toyama","jp","日本","japan",3),
("福井市","Fukui Station, Fukui","jp","日本","japan",3),
("岐阜市","Gifu Station, Gifu","jp","日本","japan",3),
("津市","Tsu Station, Mie","jp","日本","japan",3),
("和歌山市","Wakayama Station, Wakayama","jp","日本","japan",3),
("鳥取市","Tottori Station, Tottori","jp","日本","japan",3),
("松江市","Matsue Station, Shimane","jp","日本","japan",3),
("徳島市","Tokushima Station, Tokushima","jp","日本","japan",3),
("高知市","Kochi Station, Kochi","jp","日本","japan",3),
("佐賀市","Saga Station, Saga","jp","日本","japan",3),
("大分市","Oita Station, Oita","jp","日本","japan",3),
("宮崎市","Miyazaki Station, Miyazaki","jp","日本","japan",3),
("帯広市","Obihiro Station, Hokkaido","jp","日本","japan",3),
("釧路市","Kushiro Station, Hokkaido","jp","日本","japan",3),
("郡山市","Koriyama Station, Fukushima","jp","日本","japan",3),
("上越市・高田","Takada Station, Joetsu","jp","日本","japan",3),
# ================= アジア 56 =================
("ソウル・明洞","Myeongdong, Jung-gu, Seoul","kr","韓国","asia",1),
("台北101","Taipei 101","tw","台湾","asia",1),
("香港・尖沙咀","Tsim Sha Tsui, Hong Kong","hk","香港","asia",1),
("バンコク・王宮","Grand Palace, Bangkok","th","タイ","asia",1),
("マリーナベイ・サンズ","Marina Bay Sands, Singapore","sg","シンガポール","asia",1),
("ペトロナスツインタワー","Petronas Twin Towers, Kuala Lumpur","my","マレーシア","asia",1),
("ドバイ・ブルジュハリファ","Burj Khalifa, Dubai","ae","アラブ首長国連邦","asia",1),
("イスタンブール・スルタンアフメット","Sultanahmet, Istanbul","tr","トルコ","asia",1),
("タージマハル","Taj Mahal, Agra","in","インド","asia",1),
("バリ島・クタビーチ","Kuta Beach, Bali","id","インドネシア","asia",1),
("ハノイ・ホアンキエム湖","Hoan Kiem Lake, Hanoi","vn","ベトナム","asia",1),
("エルサレム旧市街","Old City, Jerusalem","il","イスラエル","asia",1),
("釜山・海雲台","Haeundae Beach, Busan","kr","韓国","asia",2),
("台南","Tainan Station, Taiwan","tw","台湾","asia",2),
("マカオ・セナド広場","Senado Square, Macau","mo","マカオ","asia",2),
("チェンマイ旧市街","Tha Phae Gate, Chiang Mai","th","タイ","asia",2),
("ホーチミン・ベンタイン市場","Ben Thanh Market, Ho Chi Minh City","vn","ベトナム","asia",2),
("プノンペン王宮","Royal Palace, Phnom Penh","kh","カンボジア","asia",2),
("シェムリアップ","Pub Street, Siem Reap","kh","カンボジア","asia",2),
("ジャカルタ・モナス","Monas, Jakarta","id","インドネシア","asia",2),
("マニラ・イントラムロス","Intramuros, Manila","ph","フィリピン","asia",2),
("セブ","Magellan's Cross, Cebu City","ph","フィリピン","asia",2),
("ムンバイ・ゲートウェイ","Gateway of India, Mumbai","in","インド","asia",2),
("デリー・インド門","India Gate, New Delhi","in","インド","asia",2),
("コロンボ","Galle Face Green, Colombo","lk","スリランカ","asia",2),
("カトマンズ・ダルバール広場","Kathmandu Durbar Square","np","ネパール","asia",2),
("アブダビ","Sheikh Zayed Grand Mosque, Abu Dhabi","ae","アラブ首長国連邦","asia",2),
("ドーハ","Souq Waqif, Doha","qa","カタール","asia",2),
("アンマン","Rainbow Street, Amman","jo","ヨルダン","asia",2),
("ペトラ遺跡","Petra, Jordan","jo","ヨルダン","asia",2),
("テルアビブ","Rothschild Boulevard, Tel Aviv","il","イスラエル","asia",2),
("アンカラ","Kizilay Square, Ankara","tr","トルコ","asia",2),
("大邱","Dongseongno, Daegu","kr","韓国","asia",3),
("光州","Gwangju Station, South Korea","kr","韓国","asia",3),
("高雄","Kaohsiung Station, Taiwan","tw","台湾","asia",3),
("台中","Taichung Station, Taiwan","tw","台湾","asia",3),
("ペナン・ジョージタウン","George Town, Penang","my","マレーシア","asia",3),
("コタキナバル","Kota Kinabalu, Sabah","my","マレーシア","asia",3),
("ジョホールバル","Johor Bahru, Malaysia","my","マレーシア","asia",3),
("スラバヤ","Surabaya, Indonesia","id","インドネシア","asia",3),
("ジョグジャカルタ","Malioboro, Yogyakarta","id","インドネシア","asia",3),
("ダバオ","Davao City, Philippines","ph","フィリピン","asia",3),
("ビエンチャン","Vientiane, Laos","la","ラオス","asia",3),
("ルアンパバーン","Luang Prabang, Laos","la","ラオス","asia",3),
("ダナン","Da Nang, Vietnam","vn","ベトナム","asia",3),
("フエ","Hue, Vietnam","vn","ベトナム","asia",3),
("チェンナイ","Marina Beach, Chennai","in","インド","asia",3),
("コルカタ","Park Street, Kolkata","in","インド","asia",3),
("ベンガルール","MG Road, Bangalore","in","インド","asia",3),
("ジャイプール","Hawa Mahal, Jaipur","in","インド","asia",3),
("ダッカ","Dhaka, Bangladesh","bd","バングラデシュ","asia",3),
("キャンディ","Kandy, Sri Lanka","lk","スリランカ","asia",3),
("ウランバートル","Sukhbaatar Square, Ulaanbaatar","mn","モンゴル","asia",3),
("アルマトイ","Almaty, Kazakhstan","kz","カザフスタン","asia",3),
("ビシュケク","Bishkek, Kyrgyzstan","kg","キルギス","asia",3),
("マスカット","Muscat, Oman","om","オマーン","asia",3),
]
