DATA = [
# ================= ヨーロッパ 66 =================
("パリ・エッフェル塔","Eiffel Tower, Paris","fr","フランス","europe",1),
("ロンドン・ビッグベン","Big Ben, London","gb","イギリス","europe",1),
("ローマ・コロッセオ","Colosseum, Rome","it","イタリア","europe",1),
("バルセロナ・サグラダファミリア","Sagrada Familia, Barcelona","es","スペイン","europe",1),
("ベルリン・ブランデンブルク門","Brandenburg Gate, Berlin","de","ドイツ","europe",1),
("アムステルダム・ダム広場","Dam Square, Amsterdam","nl","オランダ","europe",1),
("ヴェネツィア・サンマルコ広場","Piazza San Marco, Venice","it","イタリア","europe",1),
("プラハ旧市街広場","Old Town Square, Prague","cz","チェコ","europe",1),
("アテネ・アクロポリス","Acropolis, Athens","gr","ギリシャ","europe",1),
("ウィーン・シュテファン広場","Stephansplatz, Vienna","at","オーストリア","europe",1),
("ブリュッセル・グランプラス","Grand Place, Brussels","be","ベルギー","europe",1),
("リスボン・コメルシオ広場","Praca do Comercio, Lisbon","pt","ポルトガル","europe",1),
("ダブリン・テンプルバー","Temple Bar, Dublin","ie","アイルランド","europe",1),
("コペンハーゲン・ニューハウン","Nyhavn, Copenhagen","dk","デンマーク","europe",1),
("モスクワ・赤の広場","Red Square, Moscow","ru","ロシア","europe",1),
("サントリーニ島・イア","Oia, Santorini","gr","ギリシャ","europe",1),
("マドリード・プエルタデルソル","Puerta del Sol, Madrid","es","スペイン","europe",2),
("ミラノ・ドゥオモ","Duomo di Milano","it","イタリア","europe",2),
("フィレンツェ・ヴェッキオ橋","Ponte Vecchio, Florence","it","イタリア","europe",2),
("ナポリ","Piazza del Plebiscito, Naples","it","イタリア","europe",2),
("ミュンヘン・マリエン広場","Marienplatz, Munich","de","ドイツ","europe",2),
("ハンブルク","Speicherstadt, Hamburg","de","ドイツ","europe",2),
("ケルン大聖堂","Cologne Cathedral","de","ドイツ","europe",2),
("チューリッヒ","Bahnhofstrasse, Zurich","ch","スイス","europe",2),
("ジュネーヴ","Jet d'Eau, Geneva","ch","スイス","europe",2),
("ブダペスト・鎖橋","Szechenyi Chain Bridge, Budapest","hu","ハンガリー","europe",2),
("ワルシャワ旧市街","Old Town Market Place, Warsaw","pl","ポーランド","europe",2),
("クラクフ","Main Square, Krakow","pl","ポーランド","europe",2),
("ストックホルム・ガムラスタン","Gamla Stan, Stockholm","se","スウェーデン","europe",2),
("オスロ","Karl Johans gate, Oslo","no","ノルウェー","europe",2),
("ヘルシンキ大聖堂","Helsinki Cathedral","fi","フィンランド","europe",2),
("レイキャビク","Laugavegur, Reykjavik","is","アイスランド","europe",2),
("エディンバラ","Royal Mile, Edinburgh","gb","イギリス","europe",2),
("ポルト","Ribeira, Porto","pt","ポルトガル","europe",2),
("セビリア","Plaza de Espana, Seville","es","スペイン","europe",2),
("ドゥブロヴニク","Stradun, Dubrovnik","hr","クロアチア","europe",2),
("ザルツブルク","Getreidegasse, Salzburg","at","オーストリア","europe",2),
("ブルージュ","Markt, Bruges","be","ベルギー","europe",2),
("リヨン","Place Bellecour, Lyon","fr","フランス","europe",3),
("マルセイユ","Vieux Port, Marseille","fr","フランス","europe",3),
("ボルドー","Place de la Bourse, Bordeaux","fr","フランス","europe",3),
("ストラスブール","Petite France, Strasbourg","fr","フランス","europe",3),
("リール","Grand Place, Lille","fr","フランス","europe",3),
("ブリストル","Bristol, England","gb","イギリス","europe",3),
("マンチェスター","Piccadilly Gardens, Manchester","gb","イギリス","europe",3),
("グラスゴー","George Square, Glasgow","gb","イギリス","europe",3),
("カーディフ","Cardiff Castle, Wales","gb","イギリス","europe",3),
("ベルファスト","Belfast City Hall","gb","イギリス","europe",3),
("ロッテルダム","Markthal, Rotterdam","nl","オランダ","europe",3),
("ユトレヒト","Oudegracht, Utrecht","nl","オランダ","europe",3),
("ブラチスラバ","Hlavne namestie, Bratislava","sk","スロバキア","europe",3),
("リュブリャナ","Preseren Square, Ljubljana","si","スロベニア","europe",3),
("ザグレブ","Ban Jelacic Square, Zagreb","hr","クロアチア","europe",3),
("ベオグラード","Knez Mihailova, Belgrade","rs","セルビア","europe",3),
("ブカレスト","Old Town, Bucharest","ro","ルーマニア","europe",3),
("ソフィア","Vitosha Boulevard, Sofia","bg","ブルガリア","europe",3),
("タリン旧市街","Raekoja plats, Tallinn","ee","エストニア","europe",3),
("リガ","Riga Old Town","lv","ラトビア","europe",3),
("ビリニュス","Vilnius Old Town","lt","リトアニア","europe",3),
("キーウ","Khreshchatyk, Kyiv","ua","ウクライナ","europe",3),
("サンクトペテルブルク","Nevsky Prospect, Saint Petersburg","ru","ロシア","europe",3),
("ヨーテボリ","Avenyn, Gothenburg","se","スウェーデン","europe",3),
("ベルゲン","Bryggen, Bergen","no","ノルウェー","europe",3),
("トゥルク","Turku, Finland","fi","フィンランド","europe",3),
("バレンシア","Ciutat de les Arts i les Ciencies, Valencia","es","スペイン","europe",3),
("ボローニャ","Piazza Maggiore, Bologna","it","イタリア","europe",3),
]
