DATA = [
# ================= 北米 50 =================
("ニューヨーク・タイムズスクエア","Times Square, New York","us","アメリカ","namerica",1),
("ゴールデンゲートブリッジ","Golden Gate Bridge, San Francisco","us","アメリカ","namerica",1),
("ラスベガス・ストリップ","Las Vegas Strip, Nevada","us","アメリカ","namerica",1),
("グランドキャニオン","Grand Canyon Village, Arizona","us","アメリカ","namerica",1),
("ハリウッド","Hollywood Walk of Fame, Los Angeles","us","アメリカ","namerica",1),
("シカゴ・ミレニアムパーク","Millennium Park, Chicago","us","アメリカ","namerica",1),
("ワシントンDC・リンカーン記念堂","Lincoln Memorial, Washington DC","us","アメリカ","namerica",1),
("マイアミビーチ","Ocean Drive, Miami Beach","us","アメリカ","namerica",1),
("ワイキキビーチ","Waikiki Beach, Honolulu","us","アメリカ","namerica",1),
("ナイアガラの滝","Niagara Falls, Ontario","ca","カナダ","namerica",1),
("トロント・CNタワー","CN Tower, Toronto","ca","カナダ","namerica",1),
("メキシコシティ・ソカロ","Zocalo, Mexico City","mx","メキシコ","namerica",1),
("ボストン","Faneuil Hall, Boston","us","アメリカ","namerica",2),
("シアトル","Pike Place Market, Seattle","us","アメリカ","namerica",2),
("ニューオーリンズ","Bourbon Street, New Orleans","us","アメリカ","namerica",2),
("オースティン","6th Street, Austin, Texas","us","アメリカ","namerica",2),
("デンバー","16th Street Mall, Denver","us","アメリカ","namerica",2),
("サンディエゴ","Gaslamp Quarter, San Diego","us","アメリカ","namerica",2),
("ナッシュビル","Broadway, Nashville, Tennessee","us","アメリカ","namerica",2),
("フィラデルフィア","Independence Hall, Philadelphia","us","アメリカ","namerica",2),
("モニュメントバレー","Monument Valley, Utah","us","アメリカ","namerica",2),
("バンクーバー","Gastown, Vancouver","ca","カナダ","namerica",2),
("モントリオール","Old Montreal, Quebec","ca","カナダ","namerica",2),
("ケベックシティ","Chateau Frontenac, Quebec City","ca","カナダ","namerica",2),
("バンフ","Banff Avenue, Banff, Alberta","ca","カナダ","namerica",2),
("カンクン","Cancun Hotel Zone, Quintana Roo","mx","メキシコ","namerica",2),
("グアダラハラ","Guadalajara Cathedral, Jalisco","mx","メキシコ","namerica",2),
("オアハカ","Zocalo, Oaxaca de Juarez","mx","メキシコ","namerica",2),
("サンホセ","San Jose, Costa Rica","cr","コスタリカ","namerica",2),
("パナマシティ","Casco Viejo, Panama City","pa","パナマ","namerica",2),
("ピッツバーグ","Downtown Pittsburgh, Pennsylvania","us","アメリカ","namerica",3),
("クリーブランド","Downtown Cleveland, Ohio","us","アメリカ","namerica",3),
("デトロイト","Downtown Detroit, Michigan","us","アメリカ","namerica",3),
("カンザスシティ","Downtown Kansas City, Missouri","us","アメリカ","namerica",3),
("オマハ","Downtown Omaha, Nebraska","us","アメリカ","namerica",3),
("ボイシ","Downtown Boise, Idaho","us","アメリカ","namerica",3),
("アルバカーキ","Old Town, Albuquerque, New Mexico","us","アメリカ","namerica",3),
("タルサ","Downtown Tulsa, Oklahoma","us","アメリカ","namerica",3),
("リトルロック","Little Rock, Arkansas","us","アメリカ","namerica",3),
("バーミングハム","Birmingham, Alabama","us","アメリカ","namerica",3),
("アンカレッジ","Downtown Anchorage, Alaska","us","アメリカ","namerica",3),
("ソルトレイクシティ","Temple Square, Salt Lake City","us","アメリカ","namerica",3),
("ウィニペグ","The Forks, Winnipeg, Manitoba","ca","カナダ","namerica",3),
("ハリファックス","Halifax Waterfront, Nova Scotia","ca","カナダ","namerica",3),
("サスカトゥーン","Saskatoon, Saskatchewan","ca","カナダ","namerica",3),
("セントジョンズ","St. John's, Newfoundland","ca","カナダ","namerica",3),
("メリダ","Plaza Grande, Merida, Yucatan","mx","メキシコ","namerica",3),
("プエブラ","Zocalo, Puebla, Mexico","mx","メキシコ","namerica",3),
("アンティグア","Antigua Guatemala","gt","グアテマラ","namerica",3),
("ヌーク","Nuuk, Greenland","gl","グリーンランド","namerica",3),
# ================= 南米 42 =================
("リオ・コパカバーナ","Copacabana Beach, Rio de Janeiro","br","ブラジル","samerica",1),
("リオ・コルコバードの丘","Christ the Redeemer, Rio de Janeiro","br","ブラジル","samerica",1),
("サンパウロ・パウリスタ大通り","Avenida Paulista, Sao Paulo","br","ブラジル","samerica",1),
("ブエノスアイレス・オベリスコ","Obelisco de Buenos Aires","ar","アルゼンチン","samerica",1),
("イグアスの滝","Iguazu Falls, Misiones","ar","アルゼンチン","samerica",1),
("マチュピチュ","Machu Picchu, Cusco","pe","ペルー","samerica",1),
("クスコ","Plaza de Armas, Cusco","pe","ペルー","samerica",1),
("ウユニ","Uyuni, Potosi","bo","ボリビア","samerica",1),
("サンティアゴ","Plaza de Armas, Santiago","cl","チリ","samerica",1),
("カルタヘナ","Ciudad Amurallada, Cartagena","co","コロンビア","samerica",1),
("リマ・ミラフローレス","Miraflores, Lima","pe","ペルー","samerica",2),
("ボゴタ・ラカンデラリア","La Candelaria, Bogota","co","コロンビア","samerica",2),
("メデジン","Parque Lleras, Medellin","co","コロンビア","samerica",2),
("キト旧市街","Plaza Grande, Quito","ec","エクアドル","samerica",2),
("グアヤキル","Malecon 2000, Guayaquil","ec","エクアドル","samerica",2),
("モンテビデオ","Ciudad Vieja, Montevideo","uy","ウルグアイ","samerica",2),
("バルパライソ","Cerro Concepcion, Valparaiso","cl","チリ","samerica",2),
("サルバドール","Pelourinho, Salvador, Bahia","br","ブラジル","samerica",2),
("ブラジリア","Praca dos Tres Poderes, Brasilia","br","ブラジル","samerica",2),
("フォス・ド・イグアス","Foz do Iguacu, Parana","br","ブラジル","samerica",2),
("メンドーサ","Plaza Independencia, Mendoza","ar","アルゼンチン","samerica",2),
("バリローチェ","San Carlos de Bariloche, Rio Negro","ar","アルゼンチン","samerica",2),
("ラパス","Plaza Murillo, La Paz","bo","ボリビア","samerica",2),
("アスンシオン","Asuncion, Paraguay","py","パラグアイ","samerica",2),
("クリチバ","Curitiba, Parana","br","ブラジル","samerica",3),
("ポルトアレグレ","Porto Alegre, Rio Grande do Sul","br","ブラジル","samerica",3),
("ベロオリゾンテ","Belo Horizonte, Minas Gerais","br","ブラジル","samerica",3),
("レシフェ","Recife Antigo, Pernambuco","br","ブラジル","samerica",3),
("フォルタレザ","Fortaleza, Ceara","br","ブラジル","samerica",3),
("マナウス","Manaus, Amazonas","br","ブラジル","samerica",3),
("フロリアノポリス","Florianopolis, Santa Catarina","br","ブラジル","samerica",3),
("ロサリオ","Rosario, Santa Fe","ar","アルゼンチン","samerica",3),
("コルドバ","Cordoba, Argentina","ar","アルゼンチン","samerica",3),
("ウシュアイア","Ushuaia, Tierra del Fuego","ar","アルゼンチン","samerica",3),
("サルタ","Salta, Argentina","ar","アルゼンチン","samerica",3),
("プンタアレナス","Punta Arenas, Magallanes","cl","チリ","samerica",3),
("アントファガスタ","Antofagasta, Chile","cl","チリ","samerica",3),
("サンペドロデアタカマ","San Pedro de Atacama, Chile","cl","チリ","samerica",3),
("アレキパ","Plaza de Armas, Arequipa","pe","ペルー","samerica",3),
("トルヒーヨ","Trujillo, La Libertad, Peru","pe","ペルー","samerica",3),
("カリ","Cali, Valle del Cauca","co","コロンビア","samerica",3),
("プンタデルエステ","Punta del Este, Maldonado","uy","ウルグアイ","samerica",3),
]
